// dliy io - Node Registry
// Defines all available node types, their categories, properties, and execution handlers.
// Each node definition follows a standard schema so the visual editor can render them
// and the execution engine can run them.

import type { LucideIcon } from 'lucide-react';
import {
  Webhook, Clock, MousePointerClick, Github, MessageSquare, Brain,
  Code2, Database, GitBranch, Filter, Mail, FileText, Calendar, Globe,
  Sparkles, Bot, Slack, ShoppingBag, Twitter, Linkedin,
  Trello, SquareDashed, Figma, NotebookPen, Sheet, Cloud, Server, Lock,
  Bell, Search, FileCode, Terminal, FileJson, ArrowRightLeft, Split,
  Timer, Merge, Repeat, Network, BookOpen, Phone, MessageCircle,
  Video, Image, Mic, Music, Camera, MapPin, Navigation, Umbrella,
  Zap as ZapIcon, Plus, CheckSquare, ListTodo, KanbanSquare,
  Activity, AlertCircle, FileSpreadsheet, FileType, FileType2,
  Paperclip, Send, Inbox, Stamp, Building2, Briefcase,
  Users, UserPlus, UserCheck, CreditCard, Wallet, Receipt,
  TrendingDown, PieChart, BarChart3, DollarSign, Coins,
  Wifi, Radio, Antenna, Satellite, Cpu, HardDrive, MemoryStick,
  ShieldCheck, Key, Fingerprint, Eye, EyeOff, ScanLine,
  Workflow, Boxes, Layers, GitMerge, GitPullRequest, GitCommit,
  Stamp as StampIcon, Send as SendIcon, Plug, Plug2, Cable, Power,
  Rocket, Flame, Leaf, Snowflake, Sun, Moon, Star, Heart,
  ThumbsUp, Bookmark, Flag, Tag, Hash, AtSign,
  Sticker, Smile, Gift, PartyPopper
} from 'lucide-react';

export type NodeCategory =
  | 'triggers'
  | 'ai'
  | 'actions'
  | 'logic'
  | 'code'
  | 'databases'
  | 'communication'
  | 'productivity'
  | 'devops'
  | 'transform'
  | 'utilities';

export type FieldType = 'string' | 'text' | 'number' | 'boolean' | 'select' | 'json' | 'code' | 'credentials';

export interface NodeField {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  placeholder?: string;
  default?: unknown;
  options?: { label: string; value: string }[];
  language?: 'javascript' | 'python' | 'json';
  help?: string;
}

export interface NodeDefinition {
  type: string;
  name: string;
  description: string;
  category: NodeCategory;
  icon: LucideIcon;
  color: string;
  inputs: number;
  outputs: number;
  fields: NodeField[];
  run?: (inputs: Record<string, unknown>, config: Record<string, unknown>) => Promise<Record<string, unknown>>;
  popular?: boolean;
  tags?: string[];
}

export const NODE_CATEGORIES: { id: NodeCategory; label: string; color: string }[] = [
  { id: 'triggers',       label: 'Triggers',       color: '#10b981' },
  { id: 'ai',             label: 'AI',             color: '#a855f7' },
  { id: 'actions',        label: 'Actions',        color: '#3b82f6' },
  { id: 'logic',          label: 'Logic',          color: '#f59e0b' },
  { id: 'code',           label: 'Code',           color: '#0ea5e9' },
  { id: 'databases',      label: 'Databases',      color: '#ef4444' },
  { id: 'communication',  label: 'Communication',  color: '#8b5cf6' },
  { id: 'productivity',   label: 'Productivity',   color: '#14b8a6' },
  { id: 'devops',         label: 'DevOps',         color: '#64748b' },
  { id: 'transform',      label: 'Transform',      color: '#ec4899' },
  { id: 'utilities',      label: 'Utilities',      color: '#71717a' },
];

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // ============== TRIGGERS ==============
  {
    type: 'trigger.webhook',
    name: 'Webhook',
    description: 'Start the workflow when an HTTP request hits a unique URL',
    category: 'triggers',
    icon: Webhook,
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    popular: true,
    tags: ['http', 'api'],
    fields: [
      { key: 'method', label: 'HTTP Method', type: 'select', default: 'POST',
        options: ['GET','POST','PUT','PATCH','DELETE'].map(v => ({label: v, value: v})) },
      { key: 'path', label: 'Webhook Path', type: 'string', required: true, placeholder: 'my-webhook' },
      { key: 'auth', label: 'Require Auth Token', type: 'boolean', default: false },
    ],
    run: async (inputs, config) => ({ payload: inputs, method: config.method, receivedAt: new Date().toISOString() }),
  },
  {
    type: 'trigger.schedule',
    name: 'Schedule',
    description: 'Run on a cron schedule or fixed interval',
    category: 'triggers',
    icon: Clock,
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'cron', label: 'Cron Expression', type: 'string', required: true, default: '0 * * * *', help: 'e.g. "0 * * * *" = every hour' },
      { key: 'timezone', label: 'Timezone', type: 'string', default: 'UTC' },
    ],
    run: async () => ({ triggeredAt: new Date().toISOString(), scheduled: true }),
  },
  {
    type: 'trigger.manual',
    name: 'Manual Trigger',
    description: 'Start the workflow manually from the editor or API',
    category: 'triggers',
    icon: MousePointerClick,
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    fields: [
      { key: 'payload', label: 'Test Payload (JSON)', type: 'json', default: {} },
    ],
    run: async (_inputs, config) => ({ payload: config.payload ?? {}, manual: true }),
  },
  {
    type: 'trigger.event',
    name: 'Event Bus',
    description: 'Listen to events on the internal event bus',
    category: 'triggers',
    icon: Network,
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    fields: [
      { key: 'topic', label: 'Topic', type: 'string', required: true, placeholder: 'user.created' },
    ],
    run: async (inputs) => ({ event: inputs, topic: inputs.topic }),
  },

  // ============== AI ==============
  {
    type: 'ai.agent',
    name: 'AI Agent',
    description: 'Autonomous agent with tools, memory, and reasoning loop',
    category: 'ai',
    icon: Bot,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    popular: true,
    tags: ['llm', 'agent'],
    fields: [
      { key: 'model', label: 'Model', type: 'select', default: 'glm-4.6',
        options: [
          { label: 'GLM-4.6 (Z.ai)', value: 'glm-4.6' },
          { label: 'GPT-4o (OpenAI)', value: 'gpt-4o' },
          { label: 'Claude 3.5 Sonnet (Anthropic)', value: 'claude-3-5-sonnet' },
          { label: 'Llama 3.1 70B (Groq)', value: 'llama-3.1-70b' },
        ]},
      { key: 'systemPrompt', label: 'System Prompt', type: 'text', required: true,
        default: 'You are a helpful assistant. Use tools when needed.',
        placeholder: 'Define the agent persona and instructions' },
      { key: 'tools', label: 'Available Tools', type: 'select', options: [
        { label: 'HTTP Request', value: 'http' },
        { label: 'Database Query', value: 'db' },
        { label: 'Web Search', value: 'search' },
        { label: 'Code Execution', value: 'code' },
      ]},
      { key: 'maxSteps', label: 'Max Reasoning Steps', type: 'number', default: 10 },
      { key: 'temperature', label: 'Temperature', type: 'number', default: 0.7 },
    ],
    run: async (inputs, config) => ({
      agent: { model: config.model, steps: 3, toolsUsed: ['http'] },
      output: `Based on ${JSON.stringify(inputs).slice(0,40)}, I analyzed the request and produced a response.`,
      tokensUsed: 842,
    }),
  },
  {
    type: 'ai.llm',
    name: 'LLM Call',
    description: 'Single-shot completion to any supported LLM provider',
    category: 'ai',
    icon: Sparkles,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'model', label: 'Model', type: 'select', default: 'glm-4.6',
        options: [
          { label: 'GLM-4.6', value: 'glm-4.6' },
          { label: 'GLM-4-Flash', value: 'glm-4-flash' },
          { label: 'GPT-4o', value: 'gpt-4o' },
          { label: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet' },
        ]},
      { key: 'prompt', label: 'Prompt Template', type: 'text', required: true,
        placeholder: 'Summarize this: {{ $json.content }}',
        help: 'Use {{ $json.field }} to interpolate upstream data' },
      { key: 'temperature', label: 'Temperature', type: 'number', default: 0.7 },
      { key: 'maxTokens', label: 'Max Tokens', type: 'number', default: 1000 },
    ],
    run: async (_inputs, config) => ({
      text: `LLM response to: ${String(config.prompt ?? '').slice(0,50)}...`,
      model: config.model,
      usage: { prompt_tokens: 124, completion_tokens: 88, total_tokens: 212 },
    }),
  },
  {
    type: 'ai.memory',
    name: 'AI Memory',
    description: 'Store and retrieve conversational memory across executions',
    category: 'ai',
    icon: BookOpen,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'recall',
        options: [
          { label: 'Recall', value: 'recall' },
          { label: 'Store', value: 'store' },
          { label: 'Clear', value: 'clear' },
        ]},
      { key: 'sessionId', label: 'Session ID', type: 'string', placeholder: '{{ $json.userId }}' },
      { key: 'maxItems', label: 'Max Items', type: 'number', default: 20 },
    ],
    run: async (_inputs, config) => ({ memories: [], operation: config.operation }),
  },
  {
    type: 'ai.rag',
    name: 'RAG Search',
    description: 'Retrieve relevant documents from a vector store',
    category: 'ai',
    icon: Search,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'query', label: 'Query', type: 'string', required: true, placeholder: '{{ $json.question }}' },
      { key: 'index', label: 'Vector Index', type: 'string', default: 'default' },
      { key: 'topK', label: 'Top K Results', type: 'number', default: 5 },
    ],
    run: async (_inputs, config) => ({
      results: Array.from({length: Number(config.topK ?? 5)}).map((_,i)=>({
        id: `doc-${i}`, score: 0.92 - i*0.1, snippet: `Matched document ${i+1} snippet...`
      })),
    }),
  },

  // ============== CODE ==============
  {
    type: 'code.javascript',
    name: 'JavaScript',
    description: 'Run custom JavaScript with full access to upstream data',
    category: 'code',
    icon: Code2,
    color: '#facc15',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'code', label: 'Code', type: 'code', language: 'javascript', required: true,
        default: '// Access upstream data via `items`\n// Return value becomes downstream data\nconst result = items.map(i => ({\n  ...i,\n  processed: true\n}));\n\nreturn { result };' },
    ],
    run: async (inputs) => ({ result: inputs, executed: true, lang: 'javascript' }),
  },
  {
    type: 'code.python',
    name: 'Python',
    description: 'Run Python 3 code in an isolated sandbox',
    category: 'code',
    icon: Terminal,
    color: '#facc15',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'code', label: 'Code', type: 'code', language: 'python', required: true,
        default: '# Access upstream data via `items`\n# Return a dict to pass downstream\n\ndef main(items):\n    return {"result": [i for i in items]}' },
    ],
    run: async (inputs) => ({ result: inputs, executed: true, lang: 'python' }),
  },
  {
    type: 'code.jsonTransform',
    name: 'JSON Transform',
    description: 'Visually map and reshape JSON data',
    category: 'code',
    icon: FileJson,
    color: '#facc15',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'mapping', label: 'Mapping (jq-like)', type: 'text',
        default: '{ id: .id, name: .user.name, email: .user.email }' },
    ],
    run: async (inputs) => ({ transformed: inputs }),
  },

  // ============== LOGIC ==============
  {
    type: 'logic.if',
    name: 'IF / Else',
    description: 'Branch based on a condition',
    category: 'logic',
    icon: GitBranch,
    color: '#f59e0b',
    inputs: 1,
    outputs: 2,
    popular: true,
    fields: [
      { key: 'left', label: 'Value 1', type: 'string', placeholder: '{{ $json.status }}' },
      { key: 'op', label: 'Operator', type: 'select', default: 'equals',
        options: ['equals','notEquals','contains','gt','lt','gte','lte','exists'].map(v => ({label:v, value:v})) },
      { key: 'right', label: 'Value 2', type: 'string' },
    ],
    run: async (_inputs, config) => ({ branch: 'true', condition: `${config.left} ${config.op} ${config.right}` }),
  },
  {
    type: 'logic.switch',
    name: 'Switch',
    description: 'Route to one of N branches based on a value',
    category: 'logic',
    icon: Split,
    color: '#f59e0b',
    inputs: 1,
    outputs: 4,
    fields: [
      { key: 'expression', label: 'Expression', type: 'string', placeholder: '{{ $json.type }}' },
      { key: 'cases', label: 'Cases (one per line)', type: 'text', default: 'case1\ncase2\ncase3' },
    ],
    run: async (inputs, config) => ({ matched: 'case1', input: inputs }),
  },
  {
    type: 'logic.loop',
    name: 'Loop',
    description: 'Iterate over an array of items',
    category: 'logic',
    icon: Repeat,
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'array', label: 'Array Path', type: 'string', placeholder: '{{ $json.items }}' },
      { key: 'batchSize', label: 'Batch Size', type: 'number', default: 1 },
    ],
    run: async (inputs) => ({ iterated: true, items: inputs }),
  },
  {
    type: 'logic.wait',
    name: 'Wait',
    description: 'Pause the workflow for a duration',
    category: 'logic',
    icon: Timer,
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'amount', label: 'Amount', type: 'number', default: 5 },
      { key: 'unit', label: 'Unit', type: 'select', default: 'seconds',
        options: ['seconds','minutes','hours','days'].map(v => ({label:v,value:v})) },
    ],
    run: async (_inputs, config) => ({ waited: `${config.amount} ${config.unit}` }),
  },
  {
    type: 'logic.merge',
    name: 'Merge',
    description: 'Combine multiple branches back into one',
    category: 'logic',
    icon: Merge,
    color: '#f59e0b',
    inputs: -1,
    outputs: 1,
    fields: [
      { key: 'mode', label: 'Mode', type: 'select', default: 'all',
        options: [{label:'Wait for all',value:'all'},{label:'First to finish',value:'first'},{label:'By index',value:'index'}] },
    ],
    run: async (inputs) => ({ merged: inputs }),
  },
  {
    type: 'logic.filter',
    name: 'Filter',
    description: 'Drop items that do not match a condition',
    category: 'logic',
    icon: Filter,
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'expression', label: 'Filter Expression', type: 'string', placeholder: '{{ $json.value > 100 }}' },
    ],
    run: async (inputs) => ({ filtered: inputs }),
  },

  // ============== ACTIONS ==============
  {
    type: 'action.http',
    name: 'HTTP Request',
    description: 'Call any REST API or webhook',
    category: 'actions',
    icon: Globe,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'method', label: 'Method', type: 'select', default: 'GET',
        options: ['GET','POST','PUT','PATCH','DELETE'].map(v => ({label:v,value:v})) },
      { key: 'url', label: 'URL', type: 'string', required: true, placeholder: 'https://api.example.com/v1/data' },
      { key: 'headers', label: 'Headers (JSON)', type: 'json', default: {} },
      { key: 'body', label: 'Body (JSON)', type: 'json', default: {} },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', default: 30000 },
    ],
    run: async (_inputs, config) => ({
      status: 200,
      headers: { 'content-type': 'application/json' },
      body: { ok: true, url: config.url, method: config.method },
    }),
  },
  {
    type: 'action.slack',
    name: 'Slack',
    description: 'Send messages, create channels, manage Slack',
    category: 'actions',
    icon: Slack,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'sendMessage',
        options: [
          { label: 'Send Message', value: 'sendMessage' },
          { label: 'Send to Channel', value: 'sendToChannel' },
          { label: 'Create Channel', value: 'createChannel' },
          { label: 'Update Profile', value: 'updateProfile' },
        ]},
      { key: 'channel', label: 'Channel', type: 'string', placeholder: '#general' },
      { key: 'text', label: 'Message', type: 'text', placeholder: 'Hello from dliy io!' },
      { key: 'credential', label: 'Slack Credential', type: 'credentials' },
    ],
    run: async (_inputs, config) => ({ ok: true, channel: config.channel, sent: true }),
  },
  {
    type: 'action.discord',
    name: 'Discord',
    description: 'Send Discord messages via webhook or bot',
    category: 'actions',
    icon: MessageSquare,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'string', required: true },
      { key: 'content', label: 'Message', type: 'text' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.github',
    name: 'GitHub',
    description: 'Manage issues, PRs, repos, and triggers',
    category: 'actions',
    icon: Github,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createIssue',
        options: [
          { label: 'Create Issue', value: 'createIssue' },
          { label: 'Create PR', value: 'createPR' },
          { label: 'Create Release', value: 'createRelease' },
          { label: 'Add Comment', value: 'addComment' },
          { label: 'Merge PR', value: 'mergePR' },
        ]},
      { key: 'repo', label: 'Repository', type: 'string', placeholder: 'owner/repo' },
      { key: 'title', label: 'Title', type: 'string' },
      { key: 'body', label: 'Body', type: 'text' },
      { key: 'credential', label: 'GitHub Token', type: 'credentials' },
    ],
    run: async (_inputs, config) => ({ ok: true, repo: config.repo, issueNumber: 42 }),
  },
  {
    type: 'action.gitlab',
    name: 'GitLab',
    description: 'Manage GitLab projects, MRs, pipelines',
    category: 'actions',
    icon: GitBranch,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createMR',
        options: [{label:'Create MR',value:'createMR'},{label:'Trigger Pipeline',value:'triggerPipeline'}] },
      { key: 'projectId', label: 'Project ID', type: 'string' },
      { key: 'credential', label: 'GitLab Token', type: 'credentials' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.email',
    name: 'Send Email',
    description: 'Send transactional email via SMTP or provider',
    category: 'actions',
    icon: Mail,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'to', label: 'To', type: 'string', required: true, placeholder: 'user@example.com' },
      { key: 'subject', label: 'Subject', type: 'string' },
      { key: 'body', label: 'Body', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', default: 'smtp',
        options: [{label:'SMTP',value:'smtp'},{label:'SendGrid',value:'sendgrid'},{label:'Postmark',value:'postmark'}] },
    ],
    run: async (_inputs, config) => ({ ok: true, sentTo: config.to }),
  },
  {
    type: 'action.stripe',
    name: 'Stripe',
    description: 'Create charges, customers, subscriptions',
    category: 'actions',
    icon: ShoppingBag,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createCharge',
        options: [
          { label: 'Create Charge', value: 'createCharge' },
          { label: 'Create Customer', value: 'createCustomer' },
          { label: 'Create Subscription', value: 'createSubscription' },
          { label: 'Refund', value: 'refund' },
        ]},
      { key: 'amount', label: 'Amount (cents)', type: 'number' },
      { key: 'currency', label: 'Currency', type: 'string', default: 'usd' },
      { key: 'credential', label: 'Stripe Secret', type: 'credentials' },
    ],
    run: async (_inputs, config) => ({ ok: true, chargeId: 'ch_sim_123', amount: config.amount }),
  },
  {
    type: 'action.notion',
    name: 'Notion',
    description: 'Create and update Notion pages and databases',
    category: 'actions',
    icon: NotebookPen,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createPage',
        options: [{label:'Create Page',value:'createPage'},{label:'Query Database',value:'queryDatabase'}] },
      { key: 'databaseId', label: 'Database ID', type: 'string' },
      { key: 'credential', label: 'Notion Token', type: 'credentials' },
    ],
    run: async () => ({ ok: true, pageId: 'page_sim_123' }),
  },
  {
    type: 'action.airtable',
    name: 'Airtable',
    description: 'Read and write Airtable records',
    category: 'actions',
    icon: Sheet,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'create',
        options: [{label:'Create',value:'create'},{label:'Update',value:'update'},{label:'List',value:'list'}] },
      { key: 'baseId', label: 'Base ID', type: 'string' },
      { key: 'table', label: 'Table', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.hubspot',
    name: 'HubSpot',
    description: 'CRM operations: contacts, deals, companies',
    category: 'actions',
    icon: ArrowRightLeft,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createContact',
        options: [{label:'Create Contact',value:'createContact'},{label:'Create Deal',value:'createDeal'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.salesforce',
    name: 'Salesforce',
    description: 'Push leads, contacts, and opportunities',
    category: 'actions',
    icon: Cloud,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createLead',
        options: [{label:'Create Lead',value:'createLead'},{label:'Create Opportunity',value:'createOpportunity'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.twitter',
    name: 'X / Twitter',
    description: 'Post tweets, search, manage lists',
    category: 'actions',
    icon: Twitter,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'postTweet',
        options: [{label:'Post Tweet',value:'postTweet'},{label:'Search',value:'search'}] },
      { key: 'text', label: 'Tweet Text', type: 'text' },
    ],
    run: async () => ({ ok: true, tweetId: 'tweet_sim_123' }),
  },
  {
    type: 'action.linkedin',
    name: 'LinkedIn',
    description: 'Post updates and share content',
    category: 'actions',
    icon: Linkedin,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'text', label: 'Post Text', type: 'text' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.jira',
    name: 'Jira',
    description: 'Create issues, update sprints, manage projects',
    category: 'actions',
    icon: SquareDashed,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createIssue',
        options: [{label:'Create Issue',value:'createIssue'},{label:'Transition Issue',value:'transition'}] },
      { key: 'project', label: 'Project Key', type: 'string' },
    ],
    run: async () => ({ ok: true, issueKey: 'PROJ-123' }),
  },
  {
    type: 'action.trello',
    name: 'Trello',
    description: 'Create cards, lists, and boards',
    category: 'actions',
    icon: Trello,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createCard',
        options: [{label:'Create Card',value:'createCard'},{label:'Move Card',value:'moveCard'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.figma',
    name: 'Figma',
    description: 'Read Figma files and post comments',
    category: 'actions',
    icon: Figma,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'getFile',
        options: [{label:'Get File',value:'getFile'},{label:'Post Comment',value:'comment'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'action.openai',
    name: 'OpenAI',
    description: 'Generate text, images, embeddings via OpenAI API',
    category: 'actions',
    icon: Brain,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'chat',
        options: [
          { label: 'Chat Completion', value: 'chat' },
          { label: 'Generate Image', value: 'image' },
          { label: 'Transcribe Audio', value: 'transcribe' },
          { label: 'Create Embedding', value: 'embedding' },
        ]},
      { key: 'model', label: 'Model', type: 'string', default: 'gpt-4o' },
      { key: 'credential', label: 'OpenAI API Key', type: 'credentials' },
    ],
    run: async (_inputs, config) => ({ ok: true, model: config.model }),
  },
  {
    type: 'action.anthropic',
    name: 'Anthropic',
    description: 'Claude models for chat, vision, and tool use',
    category: 'actions',
    icon: Sparkles,
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'model', label: 'Model', type: 'string', default: 'claude-3-5-sonnet' },
      { key: 'credential', label: 'Anthropic API Key', type: 'credentials' },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== DATABASES ==============
  {
    type: 'db.postgres',
    name: 'PostgreSQL',
    description: 'Run SQL queries against a Postgres database',
    category: 'databases',
    icon: Database,
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'query', label: 'SQL Query', type: 'text', required: true, default: 'SELECT * FROM users LIMIT 10;' },
      { key: 'connectionId', label: 'Connection', type: 'credentials' },
    ],
    run: async (_inputs, config) => ({ rows: [], rowCount: 0, query: config.query }),
  },
  {
    type: 'db.mysql',
    name: 'MySQL',
    description: 'Run SQL queries against a MySQL database',
    category: 'databases',
    icon: Database,
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'query', label: 'SQL Query', type: 'text', required: true },
      { key: 'connectionId', label: 'Connection', type: 'credentials' },
    ],
    run: async () => ({ rows: [], rowCount: 0 }),
  },
  {
    type: 'db.mongodb',
    name: 'MongoDB',
    description: 'Find, insert, update, or delete documents',
    category: 'databases',
    icon: Database,
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'find',
        options: ['find','findOne','insertOne','updateOne','deleteOne'].map(v => ({label:v,value:v})) },
      { key: 'collection', label: 'Collection', type: 'string', required: true },
      { key: 'filter', label: 'Filter (JSON)', type: 'json', default: {} },
    ],
    run: async () => ({ docs: [] }),
  },
  {
    type: 'db.redis',
    name: 'Redis',
    description: 'Get, set, and expire keys in Redis',
    category: 'databases',
    icon: Database,
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'get',
        options: ['get','set','del','incr','expire'].map(v => ({label:v,value:v})) },
      { key: 'key', label: 'Key', type: 'string' },
    ],
    run: async () => ({ value: null }),
  },

  // ============== PRODUCTIVITY ==============
  {
    type: 'productivity.calendar',
    name: 'Google Calendar',
    description: 'Create, update, or query calendar events',
    category: 'productivity',
    icon: Calendar,
    color: '#14b8a6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createEvent',
        options: [{label:'Create Event',value:'createEvent'},{label:'List Events',value:'list'}] },
      { key: 'summary', label: 'Title', type: 'string' },
      { key: 'start', label: 'Start Time', type: 'string' },
    ],
    run: async () => ({ ok: true, eventId: 'evt_123' }),
  },
  {
    type: 'productivity.docs',
    name: 'Google Docs',
    description: 'Read and write Google Docs content',
    category: 'productivity',
    icon: FileText,
    color: '#14b8a6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'read',
        options: [{label:'Read',value:'read'},{label:'Append',value:'append'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'productivity.notion',
    name: 'Notion DB',
    description: 'Query and update Notion databases',
    category: 'productivity',
    icon: NotebookPen,
    color: '#14b8a6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'databaseId', label: 'Database ID', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== DEVOPS ==============
  {
    type: 'devops.docker',
    name: 'Docker',
    description: 'Build, push, run containers',
    category: 'devops',
    icon: Server,
    color: '#64748b',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'build',
        options: ['build','push','run','stop'].map(v => ({label:v,value:v})) },
      { key: 'image', label: 'Image', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.kubernetes',
    name: 'Kubernetes',
    description: 'Apply manifests, scale deployments, restart pods',
    category: 'devops',
    icon: Server,
    color: '#64748b',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'apply',
        options: ['apply','scale','restart','logs'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.aws',
    name: 'AWS',
    description: 'S3, Lambda, SQS, DynamoDB, and more',
    category: 'devops',
    icon: Cloud,
    color: '#64748b',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'service', label: 'Service', type: 'select', default: 's3',
        options: ['s3','lambda','sqs','dynamodb','sns','ses'].map(v => ({label:v,value:v})) },
      { key: 'operation', label: 'Operation', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== TRANSFORM ==============
  {
    type: 'transform.map',
    name: 'Map Fields',
    description: 'Rename, project, and reshape fields',
    category: 'transform',
    icon: ArrowRightLeft,
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'mapping', label: 'Field Mapping (JSON)', type: 'json',
        default: { id: '$.id', fullName: '$.user.name' } },
    ],
    run: async (inputs) => ({ mapped: inputs }),
  },
  {
    type: 'transform.parse',
    name: 'Parse',
    description: 'Parse CSV, XML, JSON strings into objects',
    category: 'transform',
    icon: FileCode,
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'format', label: 'Format', type: 'select', default: 'json',
        options: ['json','csv','xml','yaml'].map(v => ({label:v,value:v})) },
    ],
    run: async (inputs) => ({ parsed: inputs }),
  },
  {
    type: 'transform.format',
    name: 'Format',
    description: 'Format dates, numbers, and strings',
    category: 'transform',
    icon: FileText,
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'format', label: 'Format', type: 'select', default: 'date',
        options: ['date','number','currency','template'].map(v => ({label:v,value:v})) },
    ],
    run: async (inputs) => ({ formatted: inputs }),
  },

  // ============== UTILITIES ==============
  {
    type: 'utility.log',
    name: 'Log',
    description: 'Print data to execution logs',
    category: 'utilities',
    icon: Terminal,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'message', label: 'Message', type: 'text' },
      { key: 'level', label: 'Level', type: 'select', default: 'info',
        options: ['debug','info','warn','error'].map(v => ({label:v,value:v})) },
    ],
    run: async (_inputs, config) => ({ logged: true, message: config.message, level: config.level }),
  },
  {
    type: 'utility.notify',
    name: 'Notify',
    description: 'Send an in-app notification to workspace members',
    category: 'utilities',
    icon: Bell,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'message', label: 'Message', type: 'text' },
      { key: 'users', label: 'User IDs (comma-separated)', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'utility.encrypt',
    name: 'Encrypt',
    description: 'Encrypt or decrypt sensitive data',
    category: 'utilities',
    icon: Lock,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'encrypt',
        options: [{label:'Encrypt',value:'encrypt'},{label:'Decrypt',value:'decrypt'}] },
      { key: 'algorithm', label: 'Algorithm', type: 'select', default: 'aes-256-gcm',
        options: ['aes-256-gcm','aes-128-cbc'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'utility.respond',
    name: 'Respond',
    description: 'Return an HTTP response when triggered by webhook',
    category: 'utilities',
    icon: Globe,
    color: '#71717a',
    inputs: 1,
    outputs: 0,
    fields: [
      { key: 'status', label: 'Status Code', type: 'number', default: 200 },
      { key: 'body', label: 'Body (JSON)', type: 'json', default: { ok: true } },
    ],
    run: async (_inputs, config) => ({ status: config.status, body: config.body }),
  },

  // ============== COMMUNICATION (new category) ==============
  {
    type: 'comm.telegram',
    name: 'Telegram',
    description: 'Send messages, photos, files via Telegram Bot API',
    category: 'communication',
    icon: Send,
    color: '#0088cc',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'chatId', label: 'Chat ID', type: 'string', required: true, placeholder: '@channel or 123456' },
      { key: 'text', label: 'Message', type: 'text' },
      { key: 'parseMode', label: 'Parse Mode', type: 'select', default: 'HTML',
        options: ['HTML','Markdown','MarkdownV2'].map(v => ({label:v,value:v})) },
      { key: 'credential', label: 'Bot Token', type: 'credentials' },
    ],
    run: async (_inputs, config) => ({ ok: true, chatId: config.chatId, messageId: 1234 }),
  },
  {
    type: 'comm.whatsapp',
    name: 'WhatsApp',
    description: 'Send WhatsApp Business messages via Twilio or Meta API',
    category: 'communication',
    icon: Phone,
    color: '#25D366',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'to', label: 'Recipient Phone', type: 'string', required: true, placeholder: '+1234567890' },
      { key: 'text', label: 'Message', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', default: 'twilio',
        options: [{label:'Twilio',value:'twilio'},{label:'Meta Cloud API',value:'meta'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'comm.twilio',
    name: 'Twilio SMS',
    description: 'Send and receive SMS / MMS via Twilio',
    category: 'communication',
    icon: MessageCircle,
    color: '#F22F46',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'to', label: 'To', type: 'string', required: true },
      { key: 'from', label: 'From (Twilio number)', type: 'string', required: true },
      { key: 'body', label: 'Message', type: 'text' },
      { key: 'credential', label: 'Twilio Credentials', type: 'credentials' },
    ],
    run: async () => ({ ok: true, sid: 'SMxxxxx' }),
  },
  {
    type: 'comm.zoom',
    name: 'Zoom',
    description: 'Create meetings, manage webinar registrants',
    category: 'communication',
    icon: Video,
    color: '#2D8CFF',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createMeeting',
        options: [{label:'Create Meeting',value:'createMeeting'},{label:'List Meetings',value:'list'}] },
      { key: 'topic', label: 'Topic', type: 'string' },
    ],
    run: async () => ({ ok: true, joinUrl: 'https://zoom.us/j/123' }),
  },
  {
    type: 'commteams',
    name: 'MS Teams',
    description: 'Post messages to Microsoft Teams channels via webhooks',
    category: 'communication',
    icon: Users,
    color: '#6264A7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'webhookUrl', label: 'Incoming Webhook URL', type: 'string', required: true },
      { key: 'text', label: 'Message', type: 'text' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'comm.matrix',
    name: 'Matrix',
    description: 'Send messages to Matrix rooms via homeserver API',
    category: 'communication',
    icon: MessageSquare,
    color: '#0DBD8B',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'roomId', label: 'Room ID', type: 'string', required: true },
      { key: 'text', label: 'Message', type: 'text' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'comm.sms',
    name: 'SMS (Generic)',
    description: 'Send SMS via Vonage, Plivo, or Clickatell',
    category: 'communication',
    icon: Phone,
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'to', label: 'To', type: 'string', required: true },
      { key: 'body', label: 'Message', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', default: 'vonage',
        options: ['vonage','plivo','clickatell'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== SOCIAL (more) ==============
  {
    type: 'social.mastodon',
    name: 'Mastodon',
    description: 'Post toots to any Mastodon instance',
    category: 'communication',
    icon: Hash,
    color: '#6364FF',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'instance', label: 'Instance URL', type: 'string', default: 'https://mastodon.social' },
      { key: 'text', label: 'Toot', type: 'text' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'social.reddit',
    name: 'Reddit',
    description: 'Post, comment, and moderate on Reddit',
    category: 'communication',
    icon: AtSign,
    color: '#FF4500',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'submit',
        options: [{label:'Submit Post',value:'submit'},{label:'Comment',value:'comment'}] },
      { key: 'subreddit', label: 'Subreddit', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'social.youtube',
    name: 'YouTube',
    description: 'Upload videos, manage playlists, reply to comments',
    category: 'communication',
    icon: Video,
    color: '#FF0000',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'upload',
        options: [{label:'Upload Video',value:'upload'},{label:'Reply to Comment',value:'reply'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'social.instagram',
    name: 'Instagram',
    description: 'Post photos and reels via Graph API',
    category: 'communication',
    icon: Camera,
    color: '#E4405F',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'caption', label: 'Caption', type: 'text' },
      { key: 'imageUrl', label: 'Image URL', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'social.tiktok',
    name: 'TikTok',
    description: 'Post videos and manage TikTok content',
    category: 'communication',
    icon: Music,
    color: '#000000',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'videoUrl', label: 'Video URL', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== MARKETING ==============
  {
    type: 'marketing.mailchimp',
    name: 'Mailchimp',
    description: 'Add subscribers, send campaigns, manage lists',
    category: 'actions',
    icon: Mail,
    color: '#FFE01B',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'addSubscriber',
        options: [{label:'Add Subscriber',value:'addSubscriber'},{label:'Send Campaign',value:'sendCampaign'}] },
      { key: 'listId', label: 'List/Audience ID', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'marketing.sendgrid',
    name: 'SendGrid',
    description: 'Send transactional and marketing emails at scale',
    category: 'actions',
    icon: Mail,
    color: '#1A82E2',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'to', label: 'To', type: 'string', required: true },
      { key: 'templateId', label: 'Template ID', type: 'string' },
      { key: 'dynamicData', label: 'Dynamic Template Data', type: 'json', default: {} },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'marketing.intercom',
    name: 'Intercom',
    description: 'Manage contacts, conversations, and tickets',
    category: 'actions',
    icon: MessageSquare,
    color: '#1F8DED',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createContact',
        options: [{label:'Create Contact',value:'createContact'},{label:'Send Message',value:'sendMessage'}] },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'marketing.activecampaign',
    name: 'ActiveCampaign',
    description: 'Sync contacts, trigger automations, send emails',
    category: 'actions',
    icon: Mail,
    color: '#356AE6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'syncContact' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'marketing.postmark',
    name: 'Postmark',
    description: 'Reliable transactional email delivery',
    category: 'actions',
    icon: Stamp,
    color: '#FFDE00',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'to', label: 'To', type: 'string' },
      { key: 'subject', label: 'Subject', type: 'string' },
      { key: 'body', label: 'Body', type: 'text' },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== ECOMMERCE ==============
  {
    type: 'ecom.shopify',
    name: 'Shopify',
    description: 'Manage products, orders, customers, fulfillments',
    category: 'actions',
    icon: ShoppingBag,
    color: '#96BF48',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createOrder',
        options: [{label:'Create Order',value:'createOrder'},{label:'Update Product',value:'updateProduct'},{label:'Get Customer',value:'getCustomer'}] },
      { key: 'shop', label: 'Shop Domain', type: 'string' },
      { key: 'credential', label: 'Shopify Token', type: 'credentials' },
    ],
    run: async () => ({ ok: true, orderId: '#1001' }),
  },
  {
    type: 'ecom.woocommerce',
    name: 'WooCommerce',
    description: 'WordPress ecommerce — products, orders, customers',
    category: 'actions',
    icon: ShoppingBag,
    color: '#7F54B3',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createOrder' },
      { key: 'storeUrl', label: 'Store URL', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'ecom.etsy',
    name: 'Etsy',
    description: 'Manage Etsy listings and orders',
    category: 'actions',
    icon: ShoppingBag,
    color: '#F1641E',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'ecom.amazon',
    name: 'Amazon SP-API',
    description: 'Manage Amazon listings, orders, and reports',
    category: 'actions',
    icon: ShoppingBag,
    color: '#FF9900',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'ecom.bigcommerce',
    name: 'BigCommerce',
    description: 'Manage BigCommerce store products and orders',
    category: 'actions',
    icon: ShoppingBag,
    color: '#0D52FF',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },

  // ============== PRODUCTIVITY (more) ==============
  {
    type: 'prod.asana',
    name: 'Asana',
    description: 'Create tasks, projects, and manage workspaces',
    category: 'productivity',
    icon: CheckSquare,
    color: '#F06A6A',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createTask',
        options: [{label:'Create Task',value:'createTask'},{label:'Create Project',value:'createProject'}] },
      { key: 'workspace', label: 'Workspace ID', type: 'string' },
    ],
    run: async () => ({ ok: true, taskId: 'task_123' }),
  },
  {
    type: 'prod.linear',
    name: 'Linear',
    description: 'Create issues, cycles, and projects in Linear',
    category: 'productivity',
    icon: KanbanSquare,
    color: '#5E6AD2',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createIssue',
        options: [{label:'Create Issue',value:'createIssue'},{label:'Update Cycle',value:'updateCycle'}] },
      { key: 'teamId', label: 'Team ID', type: 'string' },
      { key: 'title', label: 'Title', type: 'string' },
    ],
    run: async () => ({ ok: true, issueId: 'LIN-123' }),
  },
  {
    type: 'prod.clickup',
    name: 'ClickUp',
    description: 'Manage tasks, lists, spaces in ClickUp',
    category: 'productivity',
    icon: ListTodo,
    color: '#7B68EE',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'prod.monday',
    name: 'monday.com',
    description: 'Create items and pulses on monday.com boards',
    category: 'productivity',
    icon: KanbanSquare,
    color: '#FF3D57',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'boardId', label: 'Board ID', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'prod.todoist',
    name: 'Todoist',
    description: 'Add tasks and manage projects in Todoist',
    category: 'productivity',
    icon: CheckSquare,
    color: '#E44332',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'content', label: 'Task Content', type: 'string' },
      { key: 'project', label: 'Project ID', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'prod.confluence',
    name: 'Confluence',
    description: 'Create and update Confluence pages',
    category: 'productivity',
    icon: FileText,
    color: '#172B4D',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createPage' },
      { key: 'spaceKey', label: 'Space Key', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'prod.pagerduty',
    name: 'PagerDuty',
    description: 'Trigger incidents and manage on-call schedules',
    category: 'productivity',
    icon: AlertCircle,
    color: '#06AC38',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'triggerIncident' },
      { key: 'serviceId', label: 'Service ID', type: 'string' },
    ],
    run: async () => ({ ok: true, incidentId: 'INC-001' }),
  },

  // ============== DEVOPS (more) ==============
  {
    type: 'devops.sentry',
    name: 'Sentry',
    description: 'Track errors and releases in Sentry',
    category: 'devops',
    icon: AlertCircle,
    color: '#362D59',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createRelease' },
      { key: 'org', label: 'Organization Slug', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.datadog',
    name: 'Datadog',
    description: 'Push metrics, events, and logs to Datadog',
    category: 'devops',
    icon: Activity,
    color: '#632CA6',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'sendMetric',
        options: [{label:'Send Metric',value:'sendMetric'},{label:'Post Event',value:'postEvent'}] },
      { key: 'metric', label: 'Metric Name', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.grafana',
    name: 'Grafana',
    description: 'Manage dashboards and annotations in Grafana',
    category: 'devops',
    icon: Activity,
    color: '#F46800',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.cloudflare',
    name: 'Cloudflare',
    description: 'Manage DNS, cache purge, Workers, and WAF rules',
    category: 'devops',
    icon: Cloud,
    color: '#F38020',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'purgeCache',
        options: [{label:'Purge Cache',value:'purgeCache'},{label:'Create DNS Record',value:'createDns'},{label:'Deploy Worker',value:'deployWorker'}] },
      { key: 'zoneId', label: 'Zone ID', type: 'string' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.vercel',
    name: 'Vercel',
    description: 'Trigger deployments and manage project env vars',
    category: 'devops',
    icon: Rocket,
    color: '#000000',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'deploy' },
      { key: 'projectId', label: 'Project ID', type: 'string' },
    ],
    run: async () => ({ ok: true, deploymentId: 'dpl_xxx' }),
  },
  {
    type: 'devops.netlify',
    name: 'Netlify',
    description: 'Trigger builds and manage form submissions',
    category: 'devops',
    icon: Rocket,
    color: '#00C7B7',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'siteId', label: 'Site ID', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'devops.jenkins',
    name: 'Jenkins',
    description: 'Trigger Jenkins builds and pipelines',
    category: 'devops',
    icon: Server,
    color: '#D33833',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'jobName', label: 'Job Name', type: 'string' },
      { key: 'parameters', label: 'Build Parameters', type: 'json', default: {} },
    ],
    run: async () => ({ ok: true, buildNumber: 42 }),
  },
  {
    type: 'devops.circleci',
    name: 'CircleCI',
    description: 'Trigger CircleCI pipelines',
    category: 'devops',
    icon: GitCommit,
    color: '#343434',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'project', label: 'Project', type: 'string' }],
    run: async () => ({ ok: true }),
  },

  // ============== CLOUD (more) ==============
  {
    type: 'cloud.gcp',
    name: 'Google Cloud',
    description: 'Cloud Storage, Pub/Sub, Cloud Functions, BigQuery',
    category: 'devops',
    icon: Cloud,
    color: '#4285F4',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'service', label: 'Service', type: 'select', default: 'storage',
        options: ['storage','pubsub','functions','bigquery','firestore'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'cloud.azure',
    name: 'Azure',
    description: 'Blob Storage, Service Bus, Functions, Cosmos DB',
    category: 'devops',
    icon: Cloud,
    color: '#0078D4',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'service', label: 'Service', type: 'select', default: 'blob',
        options: ['blob','servicebus','functions','cosmosdb'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'cloud.supabase',
    name: 'Supabase',
    description: 'Query Supabase Postgres, Storage, and Auth',
    category: 'databases',
    icon: Database,
    color: '#3ECF8E',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'select' },
      { key: 'table', label: 'Table', type: 'string' },
    ],
    run: async () => ({ ok: true, rows: [] }),
  },
  {
    type: 'cloud.firebase',
    name: 'Firebase',
    description: 'Firestore, Auth, Cloud Messaging, Remote Config',
    category: 'databases',
    icon: Database,
    color: '#FFCA28',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'service', label: 'Service', type: 'select', default: 'firestore',
        options: ['firestore','auth','messaging','remoteconfig'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ ok: true }),
  },

  // ============== FINANCE (more) ==============
  {
    type: 'finance.paypal',
    name: 'PayPal',
    description: 'Create orders, capture payments, issue refunds',
    category: 'actions',
    icon: Wallet,
    color: '#003087',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'createOrder' },
      { key: 'amount', label: 'Amount', type: 'number' },
    ],
    run: async () => ({ ok: true, orderId: 'PAYPAL-123' }),
  },
  {
    type: 'finance.quickbooks',
    name: 'QuickBooks',
    description: 'Create invoices, customers, and payments',
    category: 'actions',
    icon: Receipt,
    color: '#2CA01C',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'finance.xero',
    name: 'Xero',
    description: 'Create invoices and manage contacts in Xero',
    category: 'actions',
    icon: Receipt,
    color: '#13B5EA',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },
  {
    type: 'finance.plaid',
    name: 'Plaid',
    description: 'Link bank accounts and pull transaction data',
    category: 'actions',
    icon: CreditCard,
    color: '#B5E0F5',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'getTransactions' },
    ],
    run: async () => ({ ok: true, transactions: [] }),
  },

  // ============== FILES ==============
  {
    type: 'file.s3',
    name: 'AWS S3',
    description: 'Upload, download, and manage S3 objects',
    category: 'databases',
    icon: HardDrive,
    color: '#FF9900',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'upload',
        options: ['upload','download','delete','list'].map(v => ({label:v,value:v})) },
      { key: 'bucket', label: 'Bucket', type: 'string', required: true },
      { key: 'key', label: 'Key', type: 'string' },
    ],
    run: async () => ({ ok: true, etag: 'abc123' }),
  },
  {
    type: 'file.gcs',
    name: 'Google Cloud Storage',
    description: 'Upload, download, and manage GCS objects',
    category: 'databases',
    icon: HardDrive,
    color: '#4285F4',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'upload' },
      { key: 'bucket', label: 'Bucket', type: 'string', required: true },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'file.dropbox',
    name: 'Dropbox',
    description: 'Upload, download, and share Dropbox files',
    category: 'productivity',
    icon: HardDrive,
    color: '#0061FF',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'path', label: 'Path', type: 'string', placeholder: '/folder/file.txt' },
      { key: 'operation', label: 'Operation', type: 'select', default: 'upload' },
    ],
    run: async () => ({ ok: true }),
  },
  {
    type: 'file.gdrive',
    name: 'Google Drive',
    description: 'Upload, share, and search Google Drive files',
    category: 'productivity',
    icon: HardDrive,
    color: '#0F9D58',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', default: 'upload' },
      { key: 'folderId', label: 'Folder ID', type: 'string' },
    ],
    run: async () => ({ ok: true, fileId: 'file_123' }),
  },
  {
    type: 'file.onedrive',
    name: 'OneDrive',
    description: 'Manage Microsoft OneDrive files and folders',
    category: 'productivity',
    icon: HardDrive,
    color: '#0078D4',
    inputs: 1,
    outputs: 1,
    fields: [{ key: 'operation', label: 'Operation', type: 'string' }],
    run: async () => ({ ok: true }),
  },

  // ============== UTILITIES (more) ==============
  {
    type: 'utility.aiWorkflowBuilder',
    name: 'AI Workflow Builder',
    description: 'Describe a workflow in plain English — AI generates the graph',
    category: 'ai',
    icon: Sparkles,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'description', label: 'Describe the Workflow', type: 'text', required: true,
        placeholder: 'e.g. When a GitHub PR is opened, summarize it with AI and post to Slack' },
    ],
    run: async (_inputs, config) => ({
      generated: true,
      description: config.description,
      suggestedNodes: ['trigger.webhook', 'ai.llm', 'action.slack'],
    }),
  },
  {
    type: 'utility.http',
    name: 'HTTP Polling',
    description: 'Periodically poll an HTTP endpoint for new data',
    category: 'triggers',
    icon: Globe,
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    fields: [
      { key: 'url', label: 'URL', type: 'string', required: true },
      { key: 'interval', label: 'Interval (seconds)', type: 'number', default: 60 },
      { key: 'lastSeenField', label: 'Last-seen Field (for delta)', type: 'string' },
    ],
    run: async () => ({ polled: true }),
  },
  {
    type: 'utility.qrcode',
    name: 'QR Code',
    description: 'Generate a QR code from any string',
    category: 'utilities',
    icon: ScanLine,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'data', label: 'Data', type: 'string', required: true, placeholder: '{{ $json.url }}' },
      { key: 'size', label: 'Size (px)', type: 'number', default: 256 },
    ],
    run: async (_inputs, config) => ({ qrCodeUrl: `https://api.qrserver.com/v1/create-qr-code/?size=${config.size}x${config.size}&data=${encodeURIComponent(String(config.data))}` }),
  },
  {
    type: 'utility.hash',
    name: 'Hash',
    description: 'Compute MD5, SHA-1, SHA-256, SHA-512 of input',
    category: 'utilities',
    icon: Hash,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'input', label: 'Input', type: 'string', required: true },
      { key: 'algorithm', label: 'Algorithm', type: 'select', default: 'sha256',
        options: ['md5','sha1','sha256','sha512'].map(v => ({label:v,value:v})) },
    ],
    run: async (_inputs, config) => ({ hash: '0x' + '0'.repeat(64), algorithm: config.algorithm }),
  },
  {
    type: 'utility.timestamp',
    name: 'Timestamp',
    description: 'Get current time in various formats',
    category: 'utilities',
    icon: Clock,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'format', label: 'Format', type: 'select', default: 'iso',
        options: ['iso','unix','unix_ms','rfc2822','custom'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({
      iso: new Date().toISOString(),
      unix: Math.floor(Date.now() / 1000),
      unixMs: Date.now(),
    }),
  },
  {
    type: 'utility.uuid',
    name: 'UUID Generator',
    description: 'Generate UUID v4 / v7 / nanoid',
    category: 'utilities',
    icon: Key,
    color: '#71717a',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'version', label: 'Version', type: 'select', default: 'v4',
        options: ['v4','v7','nanoid'].map(v => ({label:v,value:v})) },
      { key: 'count', label: 'Count', type: 'number', default: 1 },
    ],
    run: async (_inputs, config) => ({
      uuids: Array.from({length: Number(config.count ?? 1)}).map(() => crypto.randomUUID()),
    }),
  },
  {
    type: 'utility.webhook',
    name: 'Webhook (Trigger)',
    description: 'Alias for webhook trigger — start on any HTTP request',
    category: 'triggers',
    icon: Webhook,
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    fields: [
      { key: 'path', label: 'Path', type: 'string', required: true },
      { key: 'method', label: 'Method', type: 'select', default: 'POST',
        options: ['GET','POST','PUT','PATCH','DELETE'].map(v => ({label:v,value:v})) },
    ],
    run: async () => ({ received: true }),
  },

  // ============== MORE AI ==============
  {
    type: 'ai.imageGen',
    name: 'AI Image Gen',
    description: 'Generate images from text descriptions',
    category: 'ai',
    icon: Image,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    popular: true,
    fields: [
      { key: 'prompt', label: 'Prompt', type: 'text', required: true, placeholder: 'A futuristic city at sunset, digital art' },
      { key: 'size', label: 'Size', type: 'select', default: '1024x1024',
        options: ['512x512','1024x1024','1792x1024','1024x1792'].map(v => ({label:v,value:v})) },
      { key: 'count', label: 'Number of Images', type: 'number', default: 1 },
    ],
    run: async (_inputs, config) => ({
      images: [`https://picsum.photos/seed/${encodeURIComponent(String(config.prompt).slice(0,20))}/1024/1024`],
      model: 'image-gen',
    }),
  },
  {
    type: 'ai.transcribe',
    name: 'AI Transcribe',
    description: 'Transcribe audio files to text (Whisper / GLM-Audio)',
    category: 'ai',
    icon: Mic,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'audioUrl', label: 'Audio URL', type: 'string', required: true },
      { key: 'language', label: 'Language (optional)', type: 'string', placeholder: 'en' },
    ],
    run: async () => ({ text: '[Transcribed text would appear here]', duration: 0 }),
  },
  {
    type: 'ai.sentiment',
    name: 'Sentiment Analysis',
    description: 'Classify text as positive, negative, or neutral',
    category: 'ai',
    icon: Smile,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true, placeholder: '{{ $json.message }}' },
    ],
    run: async (_inputs, config) => ({
      sentiment: 'positive',
      score: 0.87,
      text: String(config.text ?? '').slice(0, 80),
    }),
  },
  {
    type: 'ai.classify',
    name: 'Text Classifier',
    description: 'Classify text into custom categories via LLM',
    category: 'ai',
    icon: Tag,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'categories', label: 'Categories (comma-separated)', type: 'string', default: 'spam, support, sales' },
    ],
    run: async (_inputs, config) => ({ category: 'support', confidence: 0.92 }),
  },
  {
    type: 'ai.translate',
    name: 'Translate',
    description: 'Translate text between languages via LLM',
    category: 'ai',
    icon: Globe,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'from', label: 'From', type: 'string', default: 'auto' },
      { key: 'to', label: 'To', type: 'string', default: 'en' },
    ],
    run: async (_inputs, config) => ({ translated: String(config.text ?? ''), target: config.to }),
  },
  {
    type: 'ai.summarize',
    name: 'Summarize',
    description: 'Summarize long text into bullet points',
    category: 'ai',
    icon: FileText,
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    fields: [
      { key: 'text', label: 'Text', type: 'text', required: true },
      { key: 'maxWords', label: 'Max Words', type: 'number', default: 100 },
    ],
    run: async () => ({ summary: 'Key points: ...' }),
  },
];

export const NODE_MAP: Record<string, NodeDefinition> = Object.fromEntries(
  NODE_DEFINITIONS.map(n => [n.type, n])
);

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return NODE_MAP[type];
}

export function getNodesByCategory(category: NodeCategory): NodeDefinition[] {
  return NODE_DEFINITIONS.filter(n => n.category === category);
}

export function searchNodes(query: string): NodeDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return NODE_DEFINITIONS;
  return NODE_DEFINITIONS.filter(n =>
    n.name.toLowerCase().includes(q) ||
    n.description.toLowerCase().includes(q) ||
    n.type.toLowerCase().includes(q) ||
    (n.tags ?? []).some(t => t.toLowerCase().includes(q))
  );
}

export const TOTAL_NODE_COUNT = NODE_DEFINITIONS.length;
