// dliy io - Custom Node Builder
// Lets users define their own node type with custom fields and a handler.
// Generates TypeScript code they can copy into their nodes/ directory.

'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Plus, Trash2, Copy, Download, Boxes } from 'lucide-react';
import { toast } from 'sonner';

interface CustomField {
  key: string;
  label: string;
  type: 'string' | 'text' | 'number' | 'boolean' | 'select' | 'json';
  required?: boolean;
  default?: string;
}

const FIELD_TYPES: CustomField['type'][] = ['string', 'text', 'number', 'boolean', 'select', 'json'];

export function CustomNodeBuilder() {
  const [name, setName] = useState('My Custom Node');
  const [description, setDescription] = useState('Does something custom');
  const [category, setCategory] = useState('actions');
  const [fields, setFields] = useState<CustomField[]>([
    { key: 'url', label: 'URL', type: 'string', required: true },
    { key: 'method', label: 'HTTP Method', type: 'select', default: 'GET' },
  ]);
  const [handler, setHandler] = useState(`// Available: inputs, config, credential, fetch
// Return a JSON object — it becomes downstream data.
return {
  ok: true,
  received: inputs,
  at: new Date().toISOString(),
};`);

  const addField = () => {
    setFields(prev => [...prev, { key: `field${prev.length + 1}`, label: `Field ${prev.length + 1}`, type: 'string' }]);
  };
  const updateField = (i: number, patch: Partial<CustomField>) => {
    setFields(prev => prev.map((f, idx) => idx === i ? { ...f, ...patch } : f));
  };
  const removeField = (i: number) => {
    setFields(prev => prev.filter((_, idx) => idx !== i));
  };

  const typeSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

  const generatedCode = `// dliy io - Custom Node: ${name}
// Auto-generated by the Custom Node Builder
import { defineNode } from '@dliyio/node-sdk';

export default defineNode({
  type: '${category}.${typeSlug}',
  name: '${name}',
  description: '${description}',
  category: '${category}',
  inputs: 1,
  outputs: 1,
  fields: ${JSON.stringify(fields, null, 2).split('\n').map((l, i) => i === 0 ? l : '  ' + l).join('\n')},
  async run({ inputs, config, credential }) {
${handler.split('\n').map(l => '    ' + l).join('\n')}
  },
});
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    toast.success('Code copied to clipboard');
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCode], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${typeSlug}.ts`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Downloaded');
  };

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="flex items-center gap-2 text-2xl font-bold">
          <Boxes className="h-6 w-6 text-purple-500" /> Custom Node Builder
        </h1>
        <p className="text-sm text-muted-foreground">
          Define a custom node visually, then copy the TypeScript SDK code into your <code className="rounded bg-muted px-1">nodes/custom/</code> directory.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {/* Form */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Node Definition</CardTitle>
            <CardDescription className="text-xs">Basic metadata for your node</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div>
              <Label className="text-xs">Name</Label>
              <Input value={name} onChange={(e) => setName(e.target.value)} className="text-sm" />
            </div>
            <div>
              <Label className="text-xs">Description</Label>
              <Input value={description} onChange={(e) => setDescription(e.target.value)} className="text-sm" />
            </div>
            <div>
              <Label className="text-xs">Category</Label>
              <Select value={category} onValueChange={setCategory}>
                <SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {['triggers', 'actions', 'ai', 'code', 'databases', 'communication', 'productivity', 'devops', 'transform', 'utilities'].map(c => (
                    <SelectItem key={c} value={c} className="text-sm capitalize">{c}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Node Type (auto-generated)</Label>
              <Badge variant="outline" className="font-mono text-[10px]">{category}.{typeSlug}</Badge>
            </div>

            <div className="border-t pt-3">
              <div className="mb-2 flex items-center justify-between">
                <Label className="text-xs">Fields ({fields.length})</Label>
                <Button size="sm" variant="outline" className="h-7 text-xs" onClick={addField}>
                  <Plus className="mr-1 h-3 w-3" /> Add Field
                </Button>
              </div>
              <div className="space-y-2">
                {fields.map((f, i) => (
                  <div key={i} className="rounded border p-2">
                    <div className="mb-1.5 grid grid-cols-2 gap-1.5">
                      <Input
                        value={f.key}
                        onChange={(e) => updateField(i, { key: e.target.value })}
                        placeholder="key"
                        className="h-7 text-xs font-mono"
                      />
                      <Input
                        value={f.label}
                        onChange={(e) => updateField(i, { label: e.target.value })}
                        placeholder="Label"
                        className="h-7 text-xs"
                      />
                    </div>
                    <div className="flex items-center gap-1.5">
                      <Select value={f.type} onValueChange={(v) => updateField(i, { type: v as CustomField['type'] })}>
                        <SelectTrigger className="h-7 text-xs flex-1"><SelectValue /></SelectTrigger>
                        <SelectContent>
                          {FIELD_TYPES.map(t => <SelectItem key={t} value={t} className="text-xs">{t}</SelectItem>)}
                        </SelectContent>
                      </Select>
                      <Input
                        value={f.default ?? ''}
                        onChange={(e) => updateField(i, { default: e.target.value })}
                        placeholder="default"
                        className="h-7 text-xs flex-1"
                      />
                      <label className="flex items-center gap-1 text-[10px]">
                        <input
                          type="checkbox"
                          checked={f.required ?? false}
                          onChange={(e) => updateField(i, { required: e.target.checked })}
                        />
                        req
                      </label>
                      <Button size="icon" variant="ghost" className="h-7 w-7 text-red-500" onClick={() => removeField(i)}>
                        <Trash2 className="h-3 w-3" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="border-t pt-3">
              <Label className="mb-1 block text-xs">Handler Function (JavaScript)</Label>
              <Textarea
                value={handler}
                onChange={(e) => setHandler(e.target.value)}
                className="min-h-[120px] font-mono text-[11px]"
                spellCheck={false}
              />
            </div>
          </CardContent>
        </Card>

        {/* Generated code */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-base">Generated TypeScript</CardTitle>
                <CardDescription className="text-xs">Save as <code>{typeSlug}.ts</code> in <code>nodes/custom/</code></CardDescription>
              </div>
              <div className="flex gap-1">
                <Button size="sm" variant="outline" className="h-7 text-xs" onClick={handleCopy}>
                  <Copy className="mr-1 h-3 w-3" /> Copy
                </Button>
                <Button size="sm" variant="outline" className="h-7 text-xs" onClick={handleDownload}>
                  <Download className="mr-1 h-3 w-3" /> .ts
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <pre className="overflow-x-auto rounded-md bg-zinc-950 p-3 text-[11px] text-zinc-100">
              <code>{generatedCode}</code>
            </pre>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
